- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/Solo_wrld/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/Solo_wrld/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"    
  direction: GZ_TO_ROS
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/Solo_wrld/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/camera_info"
  gz_topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/image"
  gz_topic_name: "/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name : "/joint_pos0"
  gz_topic_name : "/model/Solo_wrld/joint/base_fore_joint/0/cmd_pos"
  ros_type_name : "std_msgs/msg/Float64" 
  gz_type_name : "gz.msgs.Double"
  direction : ROS_TO_GZ
- ros_topic_name : "/joint_pos1"
  gz_topic_name : "/model/Solo_wrld/joint/fore_hand_joint/0/cmd_pos"
  ros_type_name : "std_msgs/msg/Float64"
  gz_type_name : "gz.msgs.Double"
  direction : ROS_TO_GZ

