<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/ 2.0} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/ 2.0} 0 0"/>
            </collision> 
            <xacro:wheel_inertia m="1.0" r="${radius}" h="${length}" 
                                 o_xyz="0 0 0" o_rpy="${pi/ 2.0} 0 0"/>
        </link>
    </xacro:macro>
    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} 0.4 0.2"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} 0.4 0.2"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="0.4" z="0.2" 
                            o_xyz="0 0 0.1" o_rpy="0 0 0"/>
    </link>
    <xacro:wheel_link prefix="second"/>
    <xacro:wheel_link prefix="third"/>
    <link name="fourth_link">
        <visual>
            <geometry>
            <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
            <sphere radius="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="0.5" r="0.05" o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>
    <joint name="bf_bl_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>
    <joint name="base_second_joint" type="continuous">
        <parent link="base_link"/>
        <child link="second_link"/>
        <origin xyz="${-base_length/4} -0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>
    <joint name="base_third_joint" type="continuous">
        <parent link="base_link"/>
        <child link="third_link"/>
        <origin xyz="${-base_length/4} 0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    <joint name="base_fourth_joint" type="fixed">
        <parent link="base_link"/>
        <child link="fourth_link"/>
        <origin xyz="${base_length/6} 0 -0.05" rpy="0 0 0"/>

    </joint>




</robot>