<?xml version="1.0"?>
<robot name="Solo_wrld" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="arm_gz.xacro"/>

    <xacro:property name="base_l" value="0.1"/>
    <xacro:property name="base_b" value="0.1"/>
    <xacro:property name="base_h" value="0.02"/>
    <xacro:property name="fore_r" value="0.02"/>
    <xacro:property name="fore_l" value="0.3"/>

    <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy">
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia ixx="${m/12* (y*y+z*z)}" ixy="0" ixz="0"
                     iyy="${m/12* (x*x+z*z)}" iyz="0"
                     izz="${m/12* (y*y+x*x)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h o_xyz o_rpy">
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia ixx="${m/12*(3*r*r+h*h)}" ixy="0" ixz="0"
                     iyy="${m/12*(3*r*r+h*h)}" iyz="0"
                     izz="${m/12*(3*r*r+h*h)}"/>
        </inertial>
    </xacro:macro>


    <material name="orange">
        <color rgba="1 0.65 0 1"/>
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>

    <!-- <link name="bf"/> -->

    <link name="base">
        <visual>
            <geometry>
                <box size="${base_l} ${base_b} ${base_h}"/>
            </geometry>
            <origin xyz="0 0 ${base_h/2.0}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_l} ${base_b} ${base_h}"/>
            </geometry>
            <origin xyz="0 0 ${base_h/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="5.0" x="${base_l}" y="${base_b}" z="${base_h}"
                           o_xyz="0 0 ${base_h/2.0}" o_rpy="0 0 0"/>
    </link>

    <link name="fore_arm">
        <visual>
            <geometry>
                <cylinder radius="${fore_r}" length="${fore_l}"/>
            </geometry>
            <origin xyz="0 0 ${fore_l/2.0}" rpy="0 0 0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>r
                <cylinder radius="${fore_r}" length="${fore_l}"/>
            </geometry>
            <origin xyz="0 0 ${fore_l/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${fore_r}" h="${fore_l}"
                                o_xyz="0 0 ${fore_l/2.0}" o_rpy="0 0 0"/>
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${fore_r}" length="${fore_l}"/>
            </geometry>
            <origin xyz="0 0 ${fore_l/2.0}" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${fore_r}" length="${fore_l}"/>
            </geometry>
            <origin xyz="0 0 ${fore_l/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${fore_r}" h="${fore_l}"
                                o_xyz="0 0 ${fore_l/2.0}" o_rpy="0 0 0"/>
    </link>

    <!-- <joint name="bf_base_joint" type="fixed">
        <parent link="bf"/>
        <child link="base"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> -->

    <joint name="base_fore_joint" type="revolute">
        <parent link="base"/>
        <child link="fore_arm"/>
        <origin xyz="0 0 ${base_h}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <joint name="fore_hand_joint" type="revolute">
        <parent link="fore_arm"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${fore_l}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3" />
    </joint>


</robot>