<?xml version="1.0"?>
<robot name="Solo_wrld" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro"/>
    <xacro:include filename="mobile_base.xacro"/>
    <xacro:include filename="mobile_base_gz.xacro"/>
    <xacro:include filename="robotic_arm.xacro"/>
    <xacro:include filename="arm_gz.xacro"/>
    <xacro:include filename="camera.xacro"/>

    <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base"/>
        <origin xyz="${base_length/4.0} 0 0.2" rpy="0 0 0"/>
    </joint>


</robot>